### ISSUE TITLE
Broken due to changes

### ISSUE THREAD

**Issue by danielfleischer** [Alexander-Miller/mu4e-column-faces#4]
Hi, I really like your package, it adds color and readability. 

I think it recently broke due to this [commit](https://github.com/djcb/mu/commit/8ad5fd49c91f6a8eef19b7d3cbd976fcf5614d2e). 

It's part of master and 1.7.* versioning.

Really appreciate if you could take a look and/or offer some pointers for fixing this.

**Comment by Alexander-Miller** [comment]
How'd you get your hands on this version? I get my mu from the AUR, and that's still v1.6.9. I intend to only support properly released versions of mu (lack of time and plenty to do for treemacs etc), so if you are compiling straight from git you'll have to wait for a release.

Given the degree of the changes it looks like I'd have to start from almost zero, so while this package isn't exactly large, this is not the kind of thing that can be fixed with a few pointers. I'll start working on this sooner rather than later to be ready for a new version, but until then there's little for you to do but wait or downgrade, sorry.

**Comment by Alexander-Miller** [comment]
I had a look now, and the changes weren't as extensive as expected. I've pushed a 1.7-compatible version to the WIP-1.7 branch now, you can use that until the official release.

**Comment by danielfleischer** [comment]
Yes, I have mu as a git project, and follow master. There are many changes between 1.6 and 1.7 and it broke some other packages as well. Your 1.7 fix works. Thank you very much!

**Comment by danielfleischer** [comment]
I think there's a typo: https://github.com/Alexander-Miller/mu4e-column-faces/commit/2cfa36f50d2cdaf414a3991531254b2d2575f432#r60047631.

**Comment by marcelocerri** [comment]
Hi, awesome add-on! Have you considered submitting a PR to include that as a built-in feature of mu4e?

**Comment by Alexander-Miller** [comment]
> I think there's a typo: https://github.com/Alexander-Miller/mu4e-column-faces/commit/2cfa36f50d2cdaf414a3991531254b2d2575f432#r60047631.

Didn't see this comment for some reason. It's fixed now.

> Hi, awesome add-on! Have you considered submitting a PR to include that as a built-in feature of mu4e?

That was the original plan. The maintainer was rather non-committal about the extra maintenance effort (doing things properly would be more complex than the hard overrides I am pulling here) and the potential performance impact (personally I haven't noticed or measured any).  So I created this package as a compromise.

**Comment by danielfleischer** [comment]
Closing. `master` code in mu requires the `wip-1.7` branch until a release is made. Also see #5 for recent mu change.
