### ISSUE TITLE
Possible typo when defining thread-subject  ?

### ISSUE THREAD

**Issue by cwdjankoski** [Alexander-Miller/mu4e-column-faces#8]
Hello - thank you for your work and this cool package - I am relatively new to emacs and very new to `mu4e` so apologies if this is a misunderstanding from my side.  
I _believe_ that there is a tiny typo when trying to define the `mu4e-column-faces-thead-subject` face. Note the `thead` tiny mis-spelling. It happens on [this line](https://github.com/Alexander-Miller/mu4e-column-faces/blob/master/mu4e-column-faces.el#L97).
Then [later on](https://github.com/Alexander-Miller/mu4e-column-faces/blob/master/mu4e-column-faces.el#L267) when it is used it is correctly spelled.  

I was wondering if this is intended or perhaps a small omission.  
Thanks again for your work.  
Perhaps one suggestion / comment that would be immensely helpful for newcomers like myself - would be a small explanation on how exactly to use for example `mu4e-column-faces-adjust-face` to use different colours in the headers view. I am trying to figure this out at the moment and I am finding it a bit difficult to understand how to setup the variables and functions from your package in order to change the default colours in my headers view. If i manage to do this - I am more than happy to help and provide some small snippets and examples to help other fellow newcomers.  
Greetings.

**Comment by Alexander-Miller** [comment]
> I was wondering if this is intended or perhaps a small omission.

It's a typo. I've fixed it now.

> Perhaps one suggestion / comment that would be immensely helpful for newcomers like myself - would be a small explanation on how exactly to use for example mu4e-column-faces-adjust-face to use different colours in the headers view. 

Good point, I've added usage examples into their eldoc. 

When you're dealing with needing to define a function, and you don't know what it's supposed to look like you luckily have the tools in Elisp to just take a peek, so to speak. Use a value like this: `(lambda (&rest args) (message "ARGS %s" args) nil)`. This lambda will accept any and all arguments, print them, and return nil (which the caller probably knows how to handle, since everything can be nil in elisp). Once you know the shape of the input you can start looking for the parts relevant for you, and trying to return different things.

Of course it's also not exactly helpful when the eldoc says the function takes 2 instead of 4 arguments. That part is also fixed now.

**Comment by cwdjankoski** [comment]
@Alexander-Miller Thank you for the tip and thank you for expanding the docs. re-reading them now it is much more clear ⭐
